[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SMA-REACT"
authors = [{name = "Patrick Walgren and Jacob Mingear"}]
dynamic = ["version", "description"]
