# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smaeat_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from data_reader import reader

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mts_data_file_input_button = QtWidgets.QPushButton(self.centralwidget)
        self.mts_data_file_input_button.setGeometry(QtCore.QRect(80, 40, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mts_data_file_input_button.setFont(font)
        self.mts_data_file_input_button.setCheckable(False)
        self.mts_data_file_input_button.setChecked(False)
        self.mts_data_file_input_button.setObjectName("mts_data_file_input_button")
        self.file_input_label = QtWidgets.QLabel(self.centralwidget)
        self.file_input_label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.file_input_label.setFont(font)
        self.file_input_label.setObjectName("file_input_label")
        self.mts_data_input_label = QtWidgets.QLabel(self.centralwidget)
        self.mts_data_input_label.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mts_data_input_label.setFont(font)
        self.mts_data_input_label.setObjectName("mts_data_input_label")
        self.mts_data_file_display_label = QtWidgets.QLabel(self.centralwidget)
        self.mts_data_file_display_label.setGeometry(QtCore.QRect(160, 43, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mts_data_file_display_label.setFont(font)
        self.mts_data_file_display_label.setObjectName("mts_data_file_display_label")
        self.fluke_data_input_label = QtWidgets.QLabel(self.centralwidget)
        self.fluke_data_input_label.setGeometry(QtCore.QRect(10, 67, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.fluke_data_input_label.setFont(font)
        self.fluke_data_input_label.setObjectName("fluke_data_input_label")
        self.fluke_data_file_input_button = QtWidgets.QPushButton(self.centralwidget)
        self.fluke_data_file_input_button.setGeometry(QtCore.QRect(80, 67, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fluke_data_file_input_button.setFont(font)
        self.fluke_data_file_input_button.setCheckable(False)
        self.fluke_data_file_input_button.setChecked(False)
        self.fluke_data_file_input_button.setObjectName("fluke_data_file_input_button")
        self.fluke_data_file_display_label = QtWidgets.QLabel(self.centralwidget)
        self.fluke_data_file_display_label.setGeometry(QtCore.QRect(160, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.fluke_data_file_display_label.setFont(font)
        self.fluke_data_file_display_label.setObjectName("fluke_data_file_display_label")
        self.optional_label_file = QtWidgets.QLabel(self.centralwidget)
        self.optional_label_file.setGeometry(QtCore.QRect(11, 87, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.optional_label_file.setFont(font)
        self.optional_label_file.setObjectName("optional_label_file")
        self.horizontal_separator1 = QtWidgets.QFrame(self.centralwidget)
        self.horizontal_separator1.setGeometry(QtCore.QRect(0, 110, 551, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.horizontal_separator1.setFont(font)
        self.horizontal_separator1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.horizontal_separator1.setLineWidth(1)
        self.horizontal_separator1.setMidLineWidth(2)
        self.horizontal_separator1.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_separator1.setObjectName("horizontal_separator1")
        self.time_sync_label = QtWidgets.QLabel(self.centralwidget)
        self.time_sync_label.setGeometry(QtCore.QRect(320, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.time_sync_label.setFont(font)
        self.time_sync_label.setObjectName("time_sync_label")
        self.vertical_separator_file_time = QtWidgets.QFrame(self.centralwidget)
        self.vertical_separator_file_time.setGeometry(QtCore.QRect(300, 0, 20, 121))
        self.vertical_separator_file_time.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vertical_separator_file_time.setMidLineWidth(2)
        self.vertical_separator_file_time.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_separator_file_time.setObjectName("vertical_separator_file_time")
        self.time_interval_label = QtWidgets.QLabel(self.centralwidget)
        self.time_interval_label.setGeometry(QtCore.QRect(320, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.time_interval_label.setFont(font)
        self.time_interval_label.setObjectName("time_interval_label")
        self.time_interval_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.time_interval_line_edit.setGeometry(QtCore.QRect(422, 50, 51, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.time_interval_line_edit.setFont(font)
        self.time_interval_line_edit.setText("")
        self.time_interval_line_edit.setObjectName("time_interval_line_edit")
        self.end_time_label = QtWidgets.QLabel(self.centralwidget)
        self.end_time_label.setGeometry(QtCore.QRect(320, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.end_time_label.setFont(font)
        self.end_time_label.setObjectName("end_time_label")
        self.end_time_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.end_time_line_edit.setGeometry(QtCore.QRect(422, 80, 51, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.end_time_line_edit.setFont(font)
        self.end_time_line_edit.setText("")
        self.end_time_line_edit.setObjectName("end_time_line_edit")
        self.vertical_separator_time_glitch = QtWidgets.QFrame(self.centralwidget)
        self.vertical_separator_time_glitch.setGeometry(QtCore.QRect(540, 0, 20, 229))
        self.vertical_separator_time_glitch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vertical_separator_time_glitch.setMidLineWidth(2)
        self.vertical_separator_time_glitch.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_separator_time_glitch.setObjectName("vertical_separator_time_glitch")
        self.glitch_text_text = QtWidgets.QLabel(self.centralwidget)
        self.glitch_text_text.setGeometry(QtCore.QRect(560, 65, 231, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.glitch_text_text.setFont(font)
        self.glitch_text_text.setAutoFillBackground(False)
        self.glitch_text_text.setWordWrap(True)
        self.glitch_text_text.setObjectName("glitch_text_text")
        self.glitch_check_label = QtWidgets.QLabel(self.centralwidget)
        self.glitch_check_label.setGeometry(QtCore.QRect(560, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.glitch_check_label.setFont(font)
        self.glitch_check_label.setObjectName("glitch_check_label")
        self.glitch_check_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.glitch_check_dropdown.setGeometry(QtCore.QRect(560, 135, 111, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.glitch_check_dropdown.setFont(font)
        self.glitch_check_dropdown.setObjectName("glitch_check_dropdown")
        self.glitch_check_dropdown.addItem("")
        self.glitch_check_dropdown.addItem("")
        self.glitch_check_dropdown.addItem("")
        self.mts_data_selection_label = QtWidgets.QLabel(self.centralwidget)
        self.mts_data_selection_label.setGeometry(QtCore.QRect(10, 130, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mts_data_selection_label.setFont(font)
        self.mts_data_selection_label.setObjectName("mts_data_selection_label")
        self.mts_temp_select_label = QtWidgets.QLabel(self.centralwidget)
        self.mts_temp_select_label.setGeometry(QtCore.QRect(10, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mts_temp_select_label.setFont(font)
        self.mts_temp_select_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.mts_temp_select_label.setObjectName("mts_temp_select_label")
        self.mts_temp_select_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.mts_temp_select_dropdown.setGeometry(QtCore.QRect(100, 159, 91, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mts_temp_select_dropdown.setFont(font)
        self.mts_temp_select_dropdown.setObjectName("mts_temp_select_dropdown")
        self.mts_temp_select_dropdown.addItem("")
        self.disp_label = QtWidgets.QLabel(self.centralwidget)
        self.disp_label.setGeometry(QtCore.QRect(10, 192, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.disp_label.setFont(font)
        self.disp_label.setObjectName("disp_label")
        self.disp_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.disp_dropdown.setGeometry(QtCore.QRect(100, 190, 91, 22))
        self.disp_dropdown.setObjectName("disp_dropdown")
        self.disp_dropdown.addItem("")
        self.vertical_separator_data_select = QtWidgets.QFrame(self.centralwidget)
        self.vertical_separator_data_select.setGeometry(QtCore.QRect(250, 120, 20, 108))
        self.vertical_separator_data_select.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vertical_separator_data_select.setMidLineWidth(2)
        self.vertical_separator_data_select.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_separator_data_select.setObjectName("vertical_separator_data_select")
        self.fluke_data_select_label = QtWidgets.QLabel(self.centralwidget)
        self.fluke_data_select_label.setGeometry(QtCore.QRect(270, 130, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.fluke_data_select_label.setFont(font)
        self.fluke_data_select_label.setObjectName("fluke_data_select_label")
        self.fluke_temp_label = QtWidgets.QLabel(self.centralwidget)
        self.fluke_temp_label.setGeometry(QtCore.QRect(270, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fluke_temp_label.setFont(font)
        self.fluke_temp_label.setObjectName("fluke_temp_label")
        self.fluke_temp_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.fluke_temp_dropdown.setGeometry(QtCore.QRect(360, 159, 91, 22))
        self.fluke_temp_dropdown.setObjectName("fluke_temp_dropdown")
        self.fluke_temp_dropdown.addItem("")
        self.fluke_temp_blurb = QtWidgets.QLabel(self.centralwidget)
        self.fluke_temp_blurb.setGeometry(QtCore.QRect(276, 182, 171, 31))
        self.fluke_temp_blurb.setAlignment(QtCore.Qt.AlignCenter)
        self.fluke_temp_blurb.setWordWrap(True)
        self.fluke_temp_blurb.setObjectName("fluke_temp_blurb")
        self.horizontal_separator2 = QtWidgets.QFrame(self.centralwidget)
        self.horizontal_separator2.setGeometry(QtCore.QRect(0, 220, 811, 16))
        self.horizontal_separator2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.horizontal_separator2.setMidLineWidth(2)
        self.horizontal_separator2.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_separator2.setObjectName("horizontal_separator2")
        self.cross_section_label = QtWidgets.QLabel(self.centralwidget)
        self.cross_section_label.setGeometry(QtCore.QRect(10, 240, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cross_section_label.setFont(font)
        self.cross_section_label.setObjectName("cross_section_label")
        self.shape_label = QtWidgets.QLabel(self.centralwidget)
        self.shape_label.setGeometry(QtCore.QRect(10, 270, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shape_label.setFont(font)
        self.shape_label.setObjectName("shape_label")
        self.shape_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.shape_dropdown.setGeometry(QtCore.QRect(90, 268, 91, 22))
        self.shape_dropdown.setObjectName("shape_dropdown")
        self.shape_dropdown.addItem("")
        self.shape_dropdown.addItem("")
        self.shape_dropdown.addItem("")
        self.shape_dropdown.addItem("")
        self.shape_dropdown.addItem("")
        self.input_unit_label = QtWidgets.QLabel(self.centralwidget)
        self.input_unit_label.setGeometry(QtCore.QRect(10, 300, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_unit_label.setFont(font)
        self.input_unit_label.setObjectName("input_unit_label")
        self.input_unit_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.input_unit_dropdown.setGeometry(QtCore.QRect(90, 298, 91, 22))
        self.input_unit_dropdown.setObjectName("input_unit_dropdown")
        self.input_unit_dropdown.addItem("")
        self.input_unit_dropdown.addItem("")
        self.input_unit_dropdown.addItem("")
        self.input_unit_dropdown.addItem("")
        self.output_unit_label = QtWidgets.QLabel(self.centralwidget)
        self.output_unit_label.setGeometry(QtCore.QRect(10, 328, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_unit_label.setFont(font)
        self.output_unit_label.setObjectName("output_unit_label")
        self.output_unit_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.output_unit_dropdown.setGeometry(QtCore.QRect(90, 328, 91, 22))
        self.output_unit_dropdown.setObjectName("output_unit_dropdown")
        self.output_unit_dropdown.addItem("")
        self.output_unit_dropdown.addItem("")
        self.output_unit_dropdown.addItem("")
        self.output_unit_dropdown.addItem("")
        self.measurement_label = QtWidgets.QLabel(self.centralwidget)
        self.measurement_label.setGeometry(QtCore.QRect(10, 358, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.measurement_label.setFont(font)
        self.measurement_label.setObjectName("measurement_label")
        self.measurement_input = QtWidgets.QLineEdit(self.centralwidget)
        self.measurement_input.setGeometry(QtCore.QRect(90, 358, 91, 20))
        self.measurement_input.setObjectName("measurement_input")
        self.width_label = QtWidgets.QLabel(self.centralwidget)
        self.width_label.setGeometry(QtCore.QRect(10, 388, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.width_label.setFont(font)
        self.width_label.setObjectName("width_label")
        self.width_input = QtWidgets.QLineEdit(self.centralwidget)
        self.width_input.setGeometry(QtCore.QRect(90, 388, 91, 20))
        self.width_input.setObjectName("width_input")
        self.vertical_separator_csect_movavg = QtWidgets.QFrame(self.centralwidget)
        self.vertical_separator_csect_movavg.setGeometry(QtCore.QRect(303, 228, 20, 225))
        self.vertical_separator_csect_movavg.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vertical_separator_csect_movavg.setMidLineWidth(2)
        self.vertical_separator_csect_movavg.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_separator_csect_movavg.setObjectName("vertical_separator_csect_movavg")
        self.movavg_label = QtWidgets.QLabel(self.centralwidget)
        self.movavg_label.setGeometry(QtCore.QRect(320, 234, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.movavg_label.setFont(font)
        self.movavg_label.setObjectName("movavg_label")
        self.movavg_blurb = QtWidgets.QLabel(self.centralwidget)
        self.movavg_blurb.setGeometry(QtCore.QRect(320, 262, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movavg_blurb.setFont(font)
        self.movavg_blurb.setWordWrap(True)
        self.movavg_blurb.setObjectName("movavg_blurb")
        self.movavg_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.movavg_dropdown.setGeometry(QtCore.QRect(320, 320, 101, 22))
        self.movavg_dropdown.setObjectName("movavg_dropdown")
        self.movavg_dropdown.addItem("")
        self.movavg_dropdown.addItem("")
        self.movavg_dropdown.addItem("")
        self.movavg_dropdown.addItem("")
        self.movavg_dropdown.addItem("")
        self.movavg_dropdown.addItem("")
        self.mts_temp_movavg_label = QtWidgets.QLabel(self.centralwidget)
        self.mts_temp_movavg_label.setGeometry(QtCore.QRect(320, 400, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mts_temp_movavg_label.setFont(font)
        self.mts_temp_movavg_label.setObjectName("mts_temp_movavg_label")
        self.load_movavg_label = QtWidgets.QLabel(self.centralwidget)
        self.load_movavg_label.setGeometry(QtCore.QRect(320, 375, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_movavg_label.setFont(font)
        self.load_movavg_label.setObjectName("load_movavg_label")
        self.fluke_temp_movavg_label = QtWidgets.QLabel(self.centralwidget)
        self.fluke_temp_movavg_label.setGeometry(QtCore.QRect(320, 425, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fluke_temp_movavg_label.setFont(font)
        self.fluke_temp_movavg_label.setObjectName("fluke_temp_movavg_label")
        self.disp_movavg_label = QtWidgets.QLabel(self.centralwidget)
        self.disp_movavg_label.setGeometry(QtCore.QRect(320, 350, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.disp_movavg_label.setFont(font)
        self.disp_movavg_label.setObjectName("disp_movavg_label")
        self.disp_movavg_input = QtWidgets.QLineEdit(self.centralwidget)
        self.disp_movavg_input.setGeometry(QtCore.QRect(680, 350, 113, 20))
        self.disp_movavg_input.setObjectName("disp_movavg_input")
        self.load_movavg_input = QtWidgets.QLineEdit(self.centralwidget)
        self.load_movavg_input.setGeometry(QtCore.QRect(680, 375, 113, 20))
        self.load_movavg_input.setObjectName("load_movavg_input")
        self.mts_temp_movavg_input = QtWidgets.QLineEdit(self.centralwidget)
        self.mts_temp_movavg_input.setGeometry(QtCore.QRect(680, 400, 113, 20))
        self.mts_temp_movavg_input.setObjectName("mts_temp_movavg_input")
        self.fluke_temp_movavg_input = QtWidgets.QLineEdit(self.centralwidget)
        self.fluke_temp_movavg_input.setGeometry(QtCore.QRect(680, 425, 113, 20))
        self.fluke_temp_movavg_input.setObjectName("fluke_temp_movavg_input")
        self.horizontal_separator3 = QtWidgets.QFrame(self.centralwidget)
        self.horizontal_separator3.setGeometry(QtCore.QRect(0, 450, 800, 3))
        self.horizontal_separator3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.horizontal_separator3.setMidLineWidth(2)
        self.horizontal_separator3.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_separator3.setObjectName("horizontal_separator3")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(295, 460, 211, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.start_time_title = QtWidgets.QLabel(self.centralwidget)
        self.start_time_title.setGeometry(QtCore.QRect(10, 460, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.start_time_title.setFont(font)
        self.start_time_title.setObjectName("start_time_title")
        self.start_time_label = QtWidgets.QLabel(self.centralwidget)
        self.start_time_label.setGeometry(QtCore.QRect(10, 490, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_time_label.setFont(font)
        self.start_time_label.setObjectName("start_time_label")
        self.start_time_input = QtWidgets.QLineEdit(self.centralwidget)
        self.start_time_input.setGeometry(QtCore.QRect(80, 490, 113, 20))
        self.start_time_input.setObjectName("start_time_input")
        self.start_time_format = QtWidgets.QLabel(self.centralwidget)
        self.start_time_format.setGeometry(QtCore.QRect(10, 515, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_time_format.setFont(font)
        self.start_time_format.setObjectName("start_time_format")
        self.vertical_separator_stime_start = QtWidgets.QFrame(self.centralwidget)
        self.vertical_separator_stime_start.setGeometry(QtCore.QRect(210, 450, 20, 100))
        self.vertical_separator_stime_start.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vertical_separator_stime_start.setMidLineWidth(2)
        self.vertical_separator_stime_start.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_separator_stime_start.setObjectName("vertical_separator_stime_start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #  FILE INPUT SECTION
        # button clicks
        self.mts_data_file_input_button.clicked.connect(self.browseMTSFile)
        self.fluke_data_file_input_button.clicked.connect(self.browseFlukeFile)
        # hiding and wrapping labels
        self.mts_data_file_display_label.setHidden(True)
        self.mts_data_file_display_label.setWordWrap(True)
        self.fluke_data_file_display_label.setHidden(True)
        self.fluke_data_file_display_label.setWordWrap(True)

        # TIME SYNC SECTION
        self.time_interval_line_edit.editingFinished.connect(self.getTimeInfo)
        self.end_time_line_edit.editingFinished.connect(self.getTimeInfo)

        # GLITCH CHECK SECTION
        self.glitch_check_dropdown.currentIndexChanged.connect(self.getGlitchCheck)

        # CROSS SECTION INFORMATION
        # hiding labels
        self.width_label.setHidden(True)
        self.width_input.setHidden(True)
        self.width_label.setWordWrap(True)
        self.measurement_input.setHidden(True)
        self.measurement_label.setHidden(True)
        # signals
        self.shape_dropdown.currentIndexChanged.connect(self.measurement_input.clear)
        self.shape_dropdown.currentIndexChanged.connect(self.width_input.clear)
        self.shape_dropdown.currentIndexChanged.connect(self.getCSect)
        self.input_unit_dropdown.currentIndexChanged.connect(self.getCSect)
        self.output_unit_dropdown.currentIndexChanged.connect(self.getCSect)
        self.measurement_input.editingFinished.connect(self.getCSect)
        self.width_input.editingFinished.connect(self.getCSect)

        # MOVING AVERAGE FILTER SECTION
        # hiding labels
        self.mts_temp_movavg_input.setHidden(True)
        self.mts_temp_movavg_label.setHidden(True)
        self.fluke_temp_movavg_label.setHidden(True)
        self.fluke_temp_movavg_input.setHidden(True)
        self.disp_movavg_label.setHidden(True)
        self.disp_movavg_input.setHidden(True)
        self.load_movavg_label.setHidden(True)
        self.load_movavg_input.setHidden(True)
        # signals
        self.temp_movavg_checkbox.stateChanged.connect(self.getMovAvgInfo)
        self.disp_movavg_checkbox.stateChanged.connect(self.getMovAvgInfo)
        self.load_movavg_checkbox.stateChanged.connect(self.getMovAvgInfo)
        self.none_movavg_checkbox.stateChanged.connect(self.getMovAvgInfo)
        self.mts_temp_movavg_input.editingFinished.connect(self.getMovAvgInfo)
        self.fluke_temp_movavg_input.editingFinished.connect(self.getMovAvgInfo)
        self.disp_movavg_input.editingFinished.connect(self.getMovAvgInfo)
        self.load_movavg_input.editingFinished.connect(self.getMovAvgInfo)

        # MTS DATA SELECTION SECTION
        self.mts_temp_select_dropdown.currentIndexChanged.connect(self.getMTSSelections)
        self.disp_dropdown.currentIndexChanged.connect(self.getMTSSelections)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mts_data_file_input_button.setText(_translate("MainWindow", "Browse File"))
        self.file_input_label.setText(_translate("MainWindow", "File Input"))
        self.mts_data_input_label.setText(_translate("MainWindow", "MTS Data:"))
        self.mts_data_file_display_label.setText(_translate("MainWindow", "MTS_DATA.txt"))
        self.fluke_data_input_label.setText(_translate("MainWindow", "Fluke Data:"))
        self.fluke_data_file_input_button.setText(_translate("MainWindow", "Browse File"))
        self.fluke_data_file_display_label.setText(_translate("MainWindow", "FLUKE_DATA.csv"))
        self.optional_label_file.setText(_translate("MainWindow", "(Optional)"))
        self.time_sync_label.setText(_translate("MainWindow", "Time Synchronization"))
        self.time_interval_label.setText(_translate("MainWindow", "Time Interval(s):"))
        self.end_time_label.setText(_translate("MainWindow", "End Time (s):"))
        self.glitch_text_text.setText(_translate("MainWindow",
                                                 "Sometimes the MTS glitches at 0 degrees. Would you like to account for this glitch and delete all spurious zeroes?"))
        self.glitch_check_label.setText(_translate("MainWindow", "Glitch Check"))
        self.glitch_check_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.glitch_check_dropdown.setItemText(1, _translate("MainWindow", "Yes"))
        self.glitch_check_dropdown.setItemText(2, _translate("MainWindow", "No"))
        self.mts_data_selection_label.setText(_translate("MainWindow", "MTS Data Selection"))
        self.mts_temp_select_label.setText(_translate("MainWindow", "Temperature:"))
        self.mts_temp_select_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.disp_label.setText(_translate("MainWindow", "Displacement:"))
        self.disp_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.fluke_data_select_label.setText(_translate("MainWindow", "Fluke Data Selection"))
        self.fluke_temp_label.setText(_translate("MainWindow", "Temperature:"))
        self.fluke_temp_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.fluke_temp_blurb.setText(_translate("MainWindow", "(Leave blank if you have no fluke data to analyze)"))
        self.cross_section_label.setText(_translate("MainWindow", "Cross Section Information"))
        self.shape_label.setText(_translate("MainWindow", "Shape:"))
        self.shape_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.shape_dropdown.setItemText(1, _translate("MainWindow", "Circle"))
        self.shape_dropdown.setItemText(2, _translate("MainWindow", "Square"))
        self.shape_dropdown.setItemText(3, _translate("MainWindow", "Rectangle"))
        self.shape_dropdown.setItemText(4, _translate("MainWindow", "Special"))
        self.input_unit_label.setText(_translate("MainWindow", "Input Unit:"))
        self.input_unit_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.input_unit_dropdown.setItemText(1, _translate("MainWindow", "in"))
        self.input_unit_dropdown.setItemText(2, _translate("MainWindow", "mm"))
        self.input_unit_dropdown.setItemText(3, _translate("MainWindow", "m"))
        self.output_unit_label.setText(_translate("MainWindow", "Output Unit:"))
        self.output_unit_dropdown.setItemText(0, _translate("MainWindow", "Select..."))
        self.output_unit_dropdown.setItemText(1, _translate("MainWindow", "in"))
        self.output_unit_dropdown.setItemText(2, _translate("MainWindow", "mm"))
        self.output_unit_dropdown.setItemText(3, _translate("MainWindow", "m"))
        self.measurement_label.setText(_translate("MainWindow", "Side Length:"))
        self.width_label.setText(_translate("MainWindow", "Width:"))
        self.movavg_label.setText(_translate("MainWindow", "Moving Average Filter"))
        self.movavg_blurb.setText(_translate("MainWindow",
                                             "A moving average filter can be applied to temperature, load, or displaement. Would you like to apply a moving average filter to any or all of these measurements?"))
        self.mts_temp_movavg_label.setText(
            _translate("MainWindow", "Number of datapoints for MTS temperature moving average:"))
        self.load_movavg_label.setText(_translate("MainWindow", "Number of datapoints for load moving average:"))
        self.fluke_temp_movavg_label.setText(
            _translate("MainWindow", "Number of datapoints for Fluke temperature moving average:"))
        self.disp_movavg_label.setText(
            _translate("MainWindow", "Number of datapoints for displacement moving average:"))
        self.start_button.setText(_translate("MainWindow", "Start Analysis"))
        self.temp_movavg_checkbox.setText(_translate("MainWindow", "Temperature"))
        self.disp_movavg_checkbox.setText(_translate("MainWindow", "Displacement"))
        self.load_movavg_checkbox.setText(_translate("MainWindow", "Load"))
        self.none_movavg_checkbox.setText(_translate("MainWindow", "None"))

        # file input for mts data file

    def browseMTSFile(self):
        fileloc = QFileDialog.getOpenFileName(None, "Open MTS Data File", "",
                                              "All Files(*);;Text Files(*.txt);;CSV Files(*.csv);;Excel Files(*.xlsx)")
        if fileloc:
            mtsloc = str(fileloc[0])
            filename = mtsloc[mtsloc.rindex("/") + 1:]
            self.mts_data_file_display_label.setText(filename)
            self.mts_data_file_display_label.show()
            mts = reader(mtsloc)
            mts.extract()
            mts_data = mts.dataframe.copy()
            for col in mts_data.columns.tolist():
                self.mts_temp_select_dropdown.addItem(col)
                self.disp_dropdown.addItem(col)

        # file input for fluke data file

    def browseFlukeFile(self):
        fileloc = QFileDialog.getOpenFileName(None, "Open MTS Data File", "", "All Files(*)")
        if fileloc:
            flukeloc = str(fileloc[0])
            filename = flukeloc[flukeloc.rindex("/") + 1:]
            self.fluke_data_file_display_label.setText(filename)
            self.fluke_data_file_display_label.show()

        # get time interval and end time

    def getTimeInfo(self):
        interval = self.time_interval_line_edit.text()
        end_time = self.end_time_line_edit.text()
        return interval, end_time

        # get glitch check info

    def getGlitchCheck(self):
        choice = self.glitch_check_dropdown.currentText()
        return choice

        # get cross section information

    def getCSect(self):
        shape = self.shape_dropdown.currentText()
        input_unit = self.input_unit_dropdown.currentText()
        output_unit = self.output_unit_dropdown.currentText()
        csect_info = {"Shape": shape, "Input Unit": input_unit, "Output Unit": output_unit}
        if shape == "Circle":
            self.measurement_label.setText("Diameter:")
            self.measurement_input.show()
            self.measurement_label.show()
            self.width_label.setHidden(True)
            self.width_input.setHidden(True)
            csect_info["Diameter"] = self.measurement_input.text()
        elif shape == "Rectangle":
            self.measurement_input.show()
            self.measurement_label.show()
            self.measurement_label.setText("Length:")
            self.width_label.setText("Width:")
            self.width_label.show()
            self.width_input.show()
            csect_info["Length"] = self.measurement_input.text()
            csect_info["Width"] = self.width_input.text()
        elif shape == "Square":
            self.measurement_input.show()
            self.measurement_label.show()
            self.measurement_label.setText("Side Length:")
            self.width_label.setHidden(True)
            self.width_input.setHidden(True)
            csect_info["Side Length"] = self.measurement_input.text()
        elif shape == "Special":
            self.measurement_input.show()
            self.measurement_label.show()
            self.width_label.show()
            self.width_input.show()
            self.measurement_label.setText("Side Length:")
            self.width_label.setText("Hole Diameter:")
            csect_info["Side Length"] = self.measurement_input.text()
            csect_info["Hole Diameter"] = self.width_input.text()

    def getMovAvgInfo(self):
        movavg_conditions = []
        movavg_datapoints = {}
        if self.none_movavg_checkbox.isChecked():
            movavg_conditions.clear()
            self.mts_temp_movavg_input.setHidden(True)
            self.mts_temp_movavg_label.setHidden(True)
            self.fluke_temp_movavg_label.setHidden(True)
            self.fluke_temp_movavg_input.setHidden(True)
            self.disp_movavg_label.setHidden(True)
            self.disp_movavg_input.setHidden(True)
            self.load_movavg_label.setHidden(True)
            self.load_movavg_input.setHidden(True)
            self.temp_movavg_checkbox.setCheckState(False)
            self.disp_movavg_checkbox.setCheckState(False)
            self.load_movavg_checkbox.setCheckState(False)
            self.mts_temp_movavg_input.clear()
            self.fluke_temp_movavg_input.clear()
            self.disp_movavg_input.clear()
            self.load_movavg_input.clear()
            movavg_conditions.append("none")
        else:
            if self.temp_movavg_checkbox.isChecked() and self.disp_movavg_checkbox.isChecked() and self.load_movavg_checkbox.isChecked():
                movavg_conditions.append("all")
                self.mts_temp_movavg_input.show()
                self.mts_temp_movavg_label.show()
                self.fluke_temp_movavg_input.show()
                self.fluke_temp_movavg_label.show()
                self.disp_movavg_input.show()
                self.disp_movavg_label.show()
                self.load_movavg_input.show()
                self.load_movavg_label.show()
                movavg_datapoints["MTS Temperature"] = self.mts_temp_movavg_input.text()
                movavg_datapoints["Fluke Temperature"] = self.fluke_temp_movavg_input.text()
                movavg_datapoints["Displacement"] = self.disp_movavg_input.text()
                movavg_datapoints["Load"] = self.load_movavg_input.text()
            else:
                if self.temp_movavg_checkbox.isChecked():
                    movavg_conditions.append("temperature")
                    self.mts_temp_movavg_input.show()
                    self.mts_temp_movavg_label.show()
                    self.fluke_temp_movavg_input.show()
                    self.fluke_temp_movavg_label.show()
                    movavg_datapoints["MTS Temperature"] = self.mts_temp_movavg_input.text()
                    movavg_datapoints["Fluke Temperature"] = self.fluke_temp_movavg_input.text()
                else:
                    self.mts_temp_movavg_input.setHidden(True)
                    self.mts_temp_movavg_label.setHidden(True)
                    self.fluke_temp_movavg_input.setHidden(True)
                    self.fluke_temp_movavg_label.setHidden(True)
                    self.mts_temp_movavg_input.clear()
                    self.fluke_temp_movavg_input.clear()
                if self.disp_movavg_checkbox.isChecked():
                    movavg_conditions.append("displacement")
                    self.disp_movavg_input.show()
                    self.disp_movavg_label.show()
                    movavg_datapoints["Displacement"] = self.disp_movavg_input.text()
                else:
                    self.disp_movavg_input.setHidden(True)
                    self.disp_movavg_label.setHidden(True)
                    self.disp_movavg_input.clear()
                if self.load_movavg_checkbox.isChecked():
                    movavg_conditions.append("load")
                    self.load_movavg_input.show()
                    self.load_movavg_label.show()
                    movavg_datapoints["Load"] = self.load_movavg_input.text()
                else:
                    self.load_movavg_input.setHidden(True)
                    self.load_movavg_label.setHidden(True)
                    self.load_movavg_input.clear()

    def getMTSSelections(self):
        mts_temp_header = self.mts_temp_select_dropdown.currentText()
        mts_disp_header = self.disp_dropdown.currentText()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



